name: PHPStan
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      key: cache-v1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, opcache, xdebug, xml
          tools: composer, cs2pr
      - name: Get Composer cache directory
        id: composer-cache-dir
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Restore composer cache
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Remove composer.lock
        run: rm -f composer.lock
      - name: Setup Composer
        run: composer install
      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyse
